version: '3'

services:
  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - nuxt
  nuxt:
    image: nuxt
    build: .
    ports:
      - "3000:3000"
  go:
    image: go-backend
    build: ./kro-backend
    prots:
      - "800:8080"