version: '3'

services:
  nginx:
    image: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - nuxt
      - golang
  nuxt:
    image: nuxt
    build: .
    ports:
      - "3000:3000"
  golang:
    image: golang
    build: ./kro-backend
    ports:
      - "8080:8080"
